stages:
  - test-Backend
  - build-Backend
  - deploy-Backend
  - test-Frontend
  - build-Frontend
  - deploy-Frontend

variables:
  p: 'Mw!HGrF5)p#z^G.'
  u: 'jobugua97@gmail.com'


test_backend:
  stage: test-Backend
  image: htyk
  only:
  - Development
  - Production
  script:
    - echo "will run the test here"


build_backend:
  image: docker
  stage: build-Backend
  services:
    - docker:dind
  script:
    - cd backend/MyHabari/v1
    - docker build -t myhabari-be .
    - docker login -u $u -p $p
    - docker tag myhabari-be:latest mbuguanganga/myhabari-be:latest
    - docker push mbuguanganga/myhabari-be:latest
  only:
    -  Production

deploy_backend:
  stage: deploy-Backend
  image: node:20-alpine
  only:
  - Production
  script:
    - echo "will run the deployment here"




