stages:
  - test-Backend
  - build-Backend
  - deploy-Backend
  - test-Frontend
  - build-Frontend
  - deploy-Frontend

variables:
  p: 'Mw!HGrF5)p#z^G.'
  u: 'jobugua97@gmail.com'


test_backend:
  stage: test-Backend
  image: node:20-alpine
  only:
  - Development
  - Production
  script:
    - echo "will run the test here"


build_backend:
  image: docker
  stage: build-Backend
  services:
    - docker:dind
  script:
    - cd backend/MyHabari/v1
    - docker build -t myhabari-be .
    - docker login -u $u -p $p
    - docker tag myhabari-be:latest mbuguanganga/myhabari-be:latest
    - docker push mbuguanganga/myhabari-be:latest
  only:
    -  Production

deploy_backend:
  stage: deploy-Backend
  image: ubuntu
  only:
    - Production
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - chmod 600 pr/i.crt
    - ssh-add pr/i.crt
    - ssh -o StrictHostKeyChecking=no root@174.138.11.28 "cd Myhabari/Myhabari && git pull && cd Myhabari/Myhabari/backend/Myhabari/v1 && docker-compose pull && docker-compose up -d --build "





test_frontend:
  stage: test-Frontend
  image: node:20-alpine
  only:
  - Development
  - Production
  script:
    - echo "will run the test here"

build_frontend:
  image: docker
  stage: build-Backend
  services:
    - docker:dind
  script:
    - cd backend/MyHabari/v1
    - docker build -t myhabari-fe .
    - docker login -u $u -p $p
    - docker tag myhabari-fe:latest mbuguanganga/myhabari-fe:latest
    - docker push mbuguanganga/myhabari-fe:latest
  only:
    -  Production


deploy_frontend:
  stage: deploy-Frontend
  image: ubuntu
  only:
    - Production
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - chmod 600 pr/i.crt
    - ssh-add pr/i.crt
    - ssh -o StrictHostKeyChecking=no root@174.138.11.28 "cd Myhabari/Myhabari && git pull && cd Myhabari/Myhabari/frontend/Myhabari/v1 && docker-compose pull && docker-compose up -d --build "



